version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: hello-world
    AWS_REGION: us-east-1      # change to your region

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 005878674861.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=005878674861.dkr.ecr.us-east-1.amazonaws.com/hello-world
  build:
    commands:
      - echo Building the Docker image...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"hello-docker","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
